version: '3.8'
services:
  db:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ogame.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
